# Generated by Django 2.0.9 on 2018-12-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('comment_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_comment', to='webapp.Comment', verbose_name='Комментарий на комментарий')),
                ('commented_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='webapp.User', verbose_name='Комментарий пользователя')),
                ('commented_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='webapp.Article', verbose_name='Комментарий к статье')),
            ],
        ),
    ]
