# Generated by Django 2.0.9 on 2018-12-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_to_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_comment', to='webapp.Comment', verbose_name='Комментарий на комментарий'),
        ),
    ]
