# Generated by Django 2.0.9 on 2018-12-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181215_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='webapp.Article', verbose_name='Комментарий к статье'),
        ),
    ]
