# Generated by Django 2.0.9 on 2018-12-16 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181215_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('perfectly', 'perfectly'), ('good', 'good'), ('normally', 'normally'), ('bad', 'bad'), ('horrible', 'horrible')], max_length=30, verbose_name='Оценка')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000, verbose_name='Текст статьи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='webapp.User', verbose_name='Прокомментировано пользователем'),
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_rating', to='webapp.Article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='webapp.User', verbose_name='Пользователь'),
        ),
    ]
