# Generated by Django 2.0.9 on 2018-12-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181216_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='marked_by_user',
            field=models.ManyToManyField(blank=True, related_name='user_choose', to='webapp.User', verbose_name='Избранная статья'),
        ),
    ]
