# Generated by Django 2.0.9 on 2018-12-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_article_marked_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='webapp.User', verbose_name='Прокомментировано пользователем'),
        ),
    ]
